FROM nginx:alpine

ARG SSL_CERTIFICATE_FILE
ARG SSL_PRIVATE_KEY_FILE
ARG WEBSERVER_CONFIG_FILE

COPY index.html /usr/share/nginx/html/
COPY $WEBSERVER_CONFIG_FILE /etc/nginx/conf.d/
COPY $SSL_CERTIFICATE_FILE /etc/ssl/
COPY $SSL_PRIVATE_KEY_FILE /etc/ssl/
